### ISSUE TITLE
Is there a way to extract areas like downtown, tunnel bridges etc. as mentioned in the paper ?

### ISSUE THREAD

**Issue by ricky3087** [once-for-auto-driving/once_devkit#1]
Hi ,

Thank you for the dataset. I would like to ask if there is a way in devkit to extract or filter all the sequences which are downtown, tunnel etc. ?

Best

**Comment by nmzfrank** [comment]
We have uploaded the info file [region_type.txt](https://github.com/once-for-auto-driving/once_devkit/blob/master/ImageSets/region_type.txt).
