### ISSUE TITLE
LiDAR range images

### ISSUE THREAD

**Issue by vobecant** [once-for-auto-driving/once_devkit#19]
Dear authors,
would it be please possible to also share raw LiDAr readings, i.e., the range images? If not, can you please provide the exact parameters of the LiDAR?
Thanks!
Best,
Antonin.

**Comment by nmzfrank** [comment]
We use [Pandar40P](https://www.hesaitech.com/en/Pandar40P) to collect lidar data, you can find usefull information from the site.
