### ISSUE TITLE
Lidar orientation

### ISSUE THREAD

**Issue by JonasHablitzel** [once-for-auto-driving/once_devkit#20]
Hello, 
I noticed a difference in the orientation of the Lidar sensor between different Versions of the paper and your website. Because of this, I want to ask, which one of the figures is correct. In the V1 and V2 of the paper as well as the website, it is written: "_with the x-axis positive forwards, the y-axis positive to the left, and the z-axis positive upwards_". But according to the Figure in V2 the text should be saying: "_x  positive to the left, y-axis positive to the back and the z-axis positive upwards_ ", with respect to the vehicle moving forward.

V1:
<img width="443" alt="CorddsV1" src="https://user-images.githubusercontent.com/46381577/133944165-24f37605-f10b-4603-95e6-597cae4d1ca1.png">

V2:
<img width="412" alt="coords_V2" src="https://user-images.githubusercontent.com/46381577/133944171-25c9e0f6-1783-4dda-baed-4480656ce416.png">

From the provided calibrations the second Figure should be correct if the other coordinate systems are displayed correctly.

Thank you for your help,

Jonas

**Comment by nmzfrank** [comment]
Hello Jonas,

Image V2 is correct, which is 'x positive to the left, y-axis positive to the back and the z-axis positive upwards'. We will fix the text later.
