### ISSUE TITLE
ego pose meaning

### ISSUE THREAD

**Issue by turboxin** [once-for-auto-driving/once_devkit#21]
Hi there,

I notice that in your paper, pose means the transformation matrix between each two adjacent LiDAR coordinates
![image](https://user-images.githubusercontent.com/31332811/134801243-a1916759-5fa1-4dbe-a34c-22ce0b2792bb.png)

Hwever, in the documentation from [https://once-for-auto-driving.github.io/documentation.html#data_format](url), pose means relative pose to the first frame of the scene.
![image](https://user-images.githubusercontent.com/31332811/134801295-55734abd-54a3-4be4-8c60-a6768c21e154.png)

I'm wondering which one is correct?

**Comment by turboxin** [comment]
And is if a problem with the order of pose,
![image](https://user-images.githubusercontent.com/31332811/134801648-7e3d7e36-0f64-4782-8457-cd36178c076a.png)

(quat_w, quat_x, quat_y, quat_z, trans_x, trans_y, trans_z) seems wrong as it is against [https://github.com/once-for-auto-driving/once_devkit/blob/c084b5d49a029e34570d4ddb7b7011052cb955ee/once.py#L280](url),  
where from_quat takes quaternion in (x,y,z,w) format.

**Comment by nmzfrank** [comment]
In ONCE dataset, the pose infomation is relative to the first frame of the scene. You can refer to  [frame_concat](https://github.com/once-for-auto-driving/once_devkit/blob/master/once.py#L258).
