### ISSUE TITLE
When will you release the link for test set？

### ISSUE THREAD

**Issue by czy-0326** [once-for-auto-driving/once_devkit#25]
You say you will start a new stage for test set,but I donot find where we can submit the test results.

**Comment by nmzfrank** [comment]
We have reset the test phase end time and you can submit test results through https://competitions.codalab.org/competitions/33236

**Comment by mrqrs** [comment]
> You say you will start a new stage for test set,but I donot find where we can submit the test results.
Hi ,what the number of test set? I generated 15858 annos. It tells me the number of gt and pred is different.
