### ISSUE TITLE
iou3d_kernel_cpu_with_heading(gt_boxes, pred_boxes) NameError: name 'iou3d_kernel_cpu_with_heading' is not defined

### ISSUE THREAD

**Issue by zyxcambridge** [once-for-auto-driving/once_devkit#3]
iou3d_kernel_cpu_with_heading(gt_boxes, pred_boxes)
NameError: name 'iou3d_kernel_cpu_with_heading' is not defined

**Comment by nmzfrank** [comment]
Bug has been fixed in the latest commit
