### ISSUE TITLE
Could you please provide the code for visualization?

### ISSUE THREAD

**Issue by 304886938** [once-for-auto-driving/once_devkit#7]
I want to show 3D bounding boxes onto images and point cloud

**Comment by nmzfrank** [comment]
Currently we provide a function to map lidar points onto images. If you can replace the points coordinates by the box corners' coordinates in lidar coordinate system, you can easily visualize the 3D bounding boxes onto images. 
As for 3D bounding box on point cloud, we wrote some code based on mayavi. However mayavi is a 'heavy' package to install so we didn't release this part of code.

**Comment by 304886938** [comment]
Thank you for your answer !!!
