### ISSUE TITLE
The coordinate system of the point cloud is inconsistent with that given on the homepage of the website？

### ISSUE THREAD

**Issue by Fitz-liu** [once-for-auto-driving/once_devkit#8]
The coordinate system of the point cloud seems to rotate 90 degrees to the left relative to the coordinate system given on the homepage of the website
![12](https://user-images.githubusercontent.com/24975745/126254891-6b7bd299-f2ee-48ca-bba5-1246a88acbbf.png)

**Comment by Fitz-liu** [comment]
got it

**Comment by Fitz-liu** [comment]
Does anyone have this issue?

**Comment by nmzfrank** [comment]
Hello @Fitz-liu, the coordinate system in your visualization is right, which is: X axis to the left; Y axis to the back and Z axis to the top. It is our mistake that the illustration image of the sensor on homepage is inconsistent. We will fix the coordinate and correct it soon.

**Comment by Fitz-liu** [comment]
So, at present, if I want to use the data, I just need to rotate the coordinate system and the coordinate of the marked data by 90 degrees, right？

**Comment by PointsCoder** [comment]
The annotations of 3d boxes and point clouds are under the same coordinate system, so you can just use the original coordinates. Rotating it by 90 degrees is also fine following the KITTI coordinate system.

**Comment by once-for-auto-driving** [comment]
There are some typos in the descriptions of the coordinate system. We will fix those typos in the paper and website asap.

**Comment by Fitz-liu** [comment]
Ok, thanks!
